# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'TerraformConnect'
      KeyVaultName: 'webapp-kv-westus2'
      SecretsFilter: '*'
      RunAsPreJob: true
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'