# This is a pipeline for deploying infrastructure with Terraform
# This pipeline will also be used to compile code and deploy a web app to resources created
# by Terraform
# Keep it secret....keep it safe

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'TerraformConnect'
      KeyVaultName: 'webapp-kv-westus2'
      SecretsFilter: '*'
      RunAsPreJob: true
  
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'terraform.tfvars'
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'
  - task: TerraformCLI@0
    inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'TerraformConnect'
        backendAzureRmResourceGroupName: 'webapp-terraconcept-westus2'
        backendAzureRmStorageAccountName: 'terrabackenddev'
        backendAzureRmContainerName: 'terrabackend'
        backendAzureRmKey: 'dev.terraform.tfstate'
        allowTelemetryCollection: true  
  - task: TerraformCLI@0
    inputs:
      command: 'plan'
      environmentServiceName: 'TerraformConnect'
      secureVarsFile: 'terraform.tvfars'
      allowTelemetryCollection: true
      publishPlanResults: 'webappplan'
